### ISSUE TITLE
Error reading mzML File

### ISSUE THREAD

**Issue by didda6429** [wilsontom/sRm#10] opened 2017-03-29 03:48 UTC
Hi, I have a mzML file which I converted from a Agilent .d folder using msconvert from the command line with the default options. When I try to access the data using openSRMfile, it throws an error as follows
```  
    data <- openSRMfile("U:/01_PlasmaS1P_ISTD_AutoDa_ISTD_ResSummary.mzML")
    Error in match.arg(type) : object 'compression' not found
```

**Comment by wilsontom** [comment] 2017-03-30 16:09
do you get an error if you run the following;

```R
library(sRm)
xmlDoc <- read_xml("U:/01_PlasmaS1P_ISTD_AutoDa_ISTD_ResSummary.mzML")
xmlPeaks <- sRm:::binaryArrays(xmlDoc)
intensity <- sRm:::decodePeaks(xmlPeaks$value[4],size = 8)
head(intensity)
```
Thanks

Tom

**Comment by didda6429** [comment] 2017-05-30 03:38
Hi Tom,
Sorry for the lengthy delay, but I think I found the cause of my problem. Essentially, the .mzML file from my agilent .d files seems to have a slightly different order to .RAW based ones you have used. My quick fix was to extract the data by the CV code rather than the hard-coded position. 
Adithya

**Comment by wilsontom** [comment] 2017-05-31 13:52
Hi Adithya,

No worries. Your original error was caused by `sRm` not properly checking options in cvParams, so it was crashing when it detected you have compressed files. This is all fixed in the latest release.  

If you have a `.d` SRM file that you would be willing to e-mail me then I could include it in the package for more comprehensive testing.

Thanks

Tom

**Closed by wilsontom** 2017-05-31 13:52 UTC
